spring:
  profiles:
    active: a
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.16.123:3306/onebook?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: dsx123456
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  freemarker:
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**

server:
  port: 8080
